  pipeline {
    agent any

    stages {
    stage('Checkout') {
    steps {
  git branch: 'main', url: 'https://github.com/yeojeong-0824/back.git'
  }
  }

    stage('Build') {
    steps {
    sh './gradlew bootJar'
  }
  }

    stage('Deploy') {
    steps {
  sshagent(credentials: ['key-yeojeong']) {
                          // 원격 서버에 JAR 파일을 복사
                          sh 'scp -o StrictHostKeyChecking=no build/libs/yeojeong-0.0.1-SNAPSHOT.jar ubuntu@3.25.206.207/home/ubuntu/'
                          
                          // 원격 서버에서 스크립트를 실행
                          sh 'ssh -o StrictHostKeyChecking=no ubuntu@3.25.206.207 "sh /home/ubuntu/run.sh"'
    }
    }
    }
    }
  }
