pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mini0192/TeamBack.git'
            }
        }

        stage('Build') {
            steps {
                sh './gradlew bootJar'
            }
        }

        stage('Deploy') {
            steps {
                sshagent(credentials: ['key-teamback']) {
                    // 원격 서버에 JAR 파일을 복사
                    sh 'scp -o StrictHostKeyChecking=no build/libs/Team-Back-0.0.1-SNAPSHOT.jar ubuntu@13.125.0.54:/home/ubuntu/'
                    
                    // 원격 서버에서 스크립트를 실행
                    sh 'ssh -o StrictHostKeyChecking=no ubuntu@13.125.0.54 "sh /home/ubuntu/run.sh"'
                }
            }
        }
    }
}
