server:
  port: 8080

spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379

JWTKey: DevKey123
EmailPassword: ${emailPassword}

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"