spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

JWTKey: DevKey
EmailPassword: ${emailPassword}

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"