server:
  port: 8080

spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

JWTKey: DevKey12
EmailPassword: ${emailPassword}

autocomplete:
  limit: 10
  suffix: "_suffix"
  key: "autocomplete"
  score-key: "autocomplete:score"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always