name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # application.yml 파일 생성
    - name: Make yml file
      run: |
        cd ./src/main/resources
        touch ./application.yml
        
        echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
      shell: bash

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Change gradlew permissions
      run: chmod +x ./gradlew
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Docker hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        
    - name: Docker image build
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/website .
      
    - name: Docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website

  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.GCP_HOST}}
          username: ${{secrets.GCP_USERNAME}}
          key: ${{secrets.GCP_PRIVATEKEY}}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/website
            sudo docker stop website
            sudo docker container rm website
            sudo docker run -dit -p 80:8080 --name website --link redis:redis ${{secrets.DOCKERHUB_USERNAME}}/website
            sudo docker image prune -f
